import { StyleSheet } from "react-native";
import type { DarkTheme, LightTheme } from "@/constants/theme";

export const SPECIALIST_RING_SIZE = 62;
export const SPECIALIST_RING_RADIUS = SPECIALIST_RING_SIZE / 2;

export type ChatThemeColors =
  | typeof LightTheme.colors
  | typeof DarkTheme.colors;

/** Estilos de la pantalla Chat IA (`createStyles(colors)` según CONTEXTO.md). */
export function createChatIaScreenStyles(
  _colors: ChatThemeColors,
  isDark: boolean,
) {
  const rowDivider = isDark ? "rgba(255, 255, 255, 0.08)" : "rgba(0, 0, 0, 0.05)";

  return StyleSheet.create({
  container: {
    flex: 1,
  },
  layout: {
    flex: 1,
    flexDirection: "row",
  },
  contactsPanel: {
    width: 350,
    flexDirection: "column",
  },
  searchBar: {
    padding: 13,
  },
  contactsList: {
    flex: 1,
  },
  contactItem: {
    flexDirection: "row",
    padding: 12,
    borderLeftWidth: 3,
    borderBottomWidth: 1,
    borderBottomColor: rowDivider,
  },
  /** Contenedor del avatar con anillo animado encima (ver ContactSpecialistAvatarRing) */
  contactAvatarSpecialistWrap: {
    width: SPECIALIST_RING_SIZE,
    height: SPECIALIST_RING_SIZE,
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  contactAvatarSpecialistRingAnimated: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 4,
    backgroundColor: "transparent",
  },
  contactAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  contactInfo: {
    flex: 1,
    justifyContent: "center",
  },
  contactHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  contactNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 1,
    marginRight: 8,
  },
  contactHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 78,
    justifyContent: "flex-end",
    flexShrink: 0,
  },
  contactRobotSlot: {
    width: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2,
    elevation: 2,
  },
  contactTimeText: {
    minWidth: 56,
    textAlign: "right",
  },
  contactFooter: {
    flexDirection: "row",
    alignItems: "center",
  },
  unreadBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    marginLeft: 8,
  },
  botStatusDot: {
    width: 11,
    height: 11,
    borderRadius: 99,
    marginLeft: 8,
    marginRight: 2,
  },
  chatPanel: {
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  chatHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    position: "relative",
    overflow: "visible",
    zIndex: 2000,
    elevation: 20,
  },
  mobileSearchBar: {
    borderBottomWidth: 1,
    overflow: "hidden",
  },
  chatHeaderInfo: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 4,
  },
  chatAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  messagesAreaBackground: {
    flex: 1,
  },
  messagesAreaBackgroundImage: {
    opacity: 0.1,
  },
  messagesArea: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    width: "100%",
  },
  messageContainer: {
    marginBottom: 12,
    width: "100%",
    flexDirection: "row",
    position: "relative",
  },
  messageOutbound: {
    justifyContent: "flex-end",
  },
  messageInbound: {
    justifyContent: "flex-start",
  },
  messageBubble: {
    maxWidth: "75%",
    minWidth: 0,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "column",
    position: "relative",
  },
  messageFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  messageActions: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  messageActionButton: {
    padding: 4,
    borderRadius: 4,
  },
  messageEditContainer: {
    width: "100%",
  },
  messageEditInput: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    minHeight: 60,
    maxHeight: 150,
    fontSize: 14,
    textAlignVertical: "top",
  },
  messageEditActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
    gap: 8,
  },
  messageEditButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center",
  },
  messageAttachments: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  messageAttachment: {
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
    width: 150,
    height: 150,
    marginBottom: 0,
  },
  messageAttachmentMobile: {
    width: 100,
    height: 100,
  },
  messageAttachmentImage: {
    width: "100%",
    height: "100%",
  },
  messageAttachmentPlaceholder: {
    width: 150,
    height: 150,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    padding: 8,
  },
  messageInputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 12,
    marginBottom: 20,
    borderTopWidth: 1,
    gap: 8,
    overflow: "visible",
  },
  messageInputWrapper: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
  },
  messageInput: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    includeFontPadding: false,
    lineHeight: 20,
    width: "100%",
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    outlineWidth: 0,
    outlineColor: "transparent",
  },
  inputActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
    marginBottom: 0,
  },
  uploadProgressContainer: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginRight: 8,
    minWidth: 80,
    alignItems: "center",
  },
  uploadProgressContainerMessage: {
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignItems: "center",
    alignSelf: "flex-end",
    maxWidth: 200,
  },
  uploadProgressBar: {
    width: "100%",
    height: 4,
    backgroundColor: "rgba(0,0,0,0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  uploadProgressFill: {
    height: "100%",
    borderRadius: 2,
  },
  uploadProgressInline: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 8,
  },
  uploadProgressBarInline: {
    width: 60,
    height: 3,
    backgroundColor: "rgba(0,0,0,0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
    marginBottom: 0,
    elevation: 2,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  sendButtonDisabled: {
    opacity: 0.5,
    elevation: 0,
    shadowOpacity: 0,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  emptyChat: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  emptyMessages: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  filtersContainer: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  filtersScroll: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    rowGap: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  filterButton: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    minWidth: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  filterButtonSpecialist: {
    minWidth: 96,
    maxWidth: 120,
    paddingHorizontal: 10,
  },
  chatHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    position: "relative",
    zIndex: 2100,
    alignSelf: "center",
    minHeight: 40,
  },
  chatIAToggle: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  searchMessageButton: {
    padding: 8,
  },
  messageSearchBar: {
    padding: 12,
    borderBottomWidth: 1,
  },
  contactTagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 4,
  },
  contactTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  toolsContainer: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderTopWidth: 1,
  },
  toolsScroll: {
    gap: 8,
    paddingRight: 12,
  },
  toolButton: {
    minWidth: 60,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    marginRight: 8,
  },
  contactInfoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
  },
  contactInfoAvatarContainer: {
    alignItems: "center",
    padding: 24,
  },
  contactInfoAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  contactInfoActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  contactInfoActionButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  contactInfoCollapsibleHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 12,
    borderBottomWidth: 1,
    marginBottom: 12,
    width: 20,
  },
  accordionContent: {
    paddingTop: 8,
    paddingBottom: 8,
  },
  contactInfoDetails: {
    gap: 12,
    width: "100%",
  },
  contactInfoDetailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    width: "100%",
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  infoTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  contactInfoModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
  },
  attachedFilesContainer: {
    padding: 0,
    marginBottom: 0,
    borderRadius: 0,
    width: "100%",
    borderBottomWidth: 1,
  },
  attachedFilesHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
  },
  attachedFilesCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  attachedFilesScrollContent: {
    padding: 8,
    paddingTop: 12,
    gap: 8,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    flexGrow: 1,
  },
  attachedFileThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 12,
    borderWidth: 2,
    overflow: "hidden",
    position: "relative",
  },
  attachedFileThumbnailDocument: {
    height: "auto",
    minHeight: 80,
    paddingBottom: 8,
    overflow: "visible",
  },
  attachedFileThumbnailImage: {
    width: "100%",
    height: "100%",
  },
  attachedFileThumbnailIcon: {
    width: "100%",
    height: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  attachedFileIconImage: {
    width: 40,
    height: 40,
  },
  attachedFileName: {
    fontSize: 9,
    textAlign: "center",
    marginTop: 4,
    paddingHorizontal: 4,
    maxWidth: 80,
    lineHeight: 11,
  },
  attachedFileRemoveButton: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  attachmentMenu: {
    position: "absolute",
    left: 0,
    bottom: "100%",
    width: 280,
    maxHeight: 400,
    borderRadius: 12,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    marginBottom: 8,
    zIndex: 1000,
  },
  attachmentMenuScroll: {
    maxHeight: 400,
  },
  attachmentMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? "rgba(255, 255, 255, 0.12)" : "rgba(0,0,0,0.1)",
  },
  attachmentMenuIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  attachmentMenuText: {
    flex: 1,
  },
  // Estilos para modal de visualización de imágenes
  imageViewerOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  imageViewerHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    zIndex: 10,
  },
  imageViewerCloseButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  imageViewerCloseButtonTopRight: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  imageViewerDownloadButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  imageViewerContent: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  imageViewerBody: {
    flex: 1,
    width: "100%",
  },
  imageViewerBodyRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  imageViewerBodyStack: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  imageViewerImageColumn: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    position: "relative",
    justifyContent: "center",
  },
  imageViewerDetailPanel: {
    backgroundColor: "rgba(28, 28, 32, 0.96)",
    borderColor: "rgba(255, 255, 255, 0.14)",
  },
  imageViewerDetailPanelDesktop: {
    width: 520,
    maxWidth: "55%",
    flexGrow: 0,
    flexShrink: 0,
    borderLeftWidth: 1,
    maxHeight: "100%",
  },
  imageViewerDetailPanelMobile: {
    width: "100%",
    maxHeight: 280,
    flexGrow: 0,
    borderTopWidth: 1,
  },
  imageViewerDetailPanelContent: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 16,
  },
  imageViewerDetailHeader: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  imageViewerDetailTitle: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  imageViewerDetailFieldLabel: {
    color: "rgba(255, 255, 255, 0.72)",
    fontWeight: "600",
  },
  imageViewerDetailFieldValue: {
    color: "#F3F4F6",
  },
  imageViewerNavButton: {
    position: "absolute",
    left: 16,
    top: "50%",
    transform: [{ translateY: -16 }],
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  imageViewerNavButtonRight: {
    left: "auto",
    right: 16,
  },
  imageViewerImageContainer: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  imageViewerImage: {
    width: "100%",
    height: "100%",
  },
  imageViewerThumbnails: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    paddingVertical: 8,
  },
  imageViewerThumbnailsContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  imageViewerThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "transparent",
  },
  imageViewerThumbnailActive: {
    borderColor: "#FFFFFF",
  },
  imageViewerThumbnailImage: {
    width: "100%",
    height: "100%",
  },
  // Estilos para menú contextual
  messageMenuButton: {
    padding: 4,
    marginLeft: 4,
    alignSelf: "flex-end",
  },
  messageMenuButtonInside: {
    position: "absolute",
    top: 8,
    right: 8,
    padding: 4,
    zIndex: 10,
  },
  messageContextMenu: {
    position: "absolute",
    top: 28, // Justo debajo de la flecha (top: 8 + icono ~16px + padding)
    minWidth: 180,
    borderRadius: 8,
    borderWidth: 1,
    paddingVertical: 4,
    zIndex: 10000,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 20,
  },
  /** outbound: menú hacia la izquierda, alineado con la flecha */
  messageContextMenuOutbound: {
    right: 8,
  },
  /** inbound: a la derecha del bubble; -8 px alinea con el botón de la flecha (también right: 8) */
  messageContextMenuInbound: {
    left: "100%",
    marginLeft: -10,
  },
  messageContextMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  // Estilos para responder mensaje
  replyMessageContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  replyMessageIndicator: {
    width: 4,
    height: "100%",
    marginRight: 12,
    borderRadius: 2,
  },
  replyMessageContent: {
    flex: 1,
  },
  replyMessageThumbnail: {
    marginRight: 8,
    marginLeft: 8,
  },
  replyMessageClose: {
    padding: 4,
    marginLeft: 8,
  },
  // Estilos para modal de edición
  editModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  editModalContainer: {
    width: "90%",
    maxWidth: 500,
    borderRadius: 12,
    overflow: "hidden",
  },
  editModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  editModalCloseButton: {
    padding: 4,
  },
  editModalContent: {
    padding: 16,
  },
  editModalInput: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    minHeight: 100,
    maxHeight: 200,
    fontSize: 15,
    textAlignVertical: "top",
  },
  editModalFooter: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    gap: 8,
  },
  editModalButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 100,
  },
  // Estilos para cita de mensaje
  messageQuote: {
    marginBottom: 8,
    padding: 8,
    borderRadius: 6,
    borderLeftWidth: 3,
    overflow: "hidden",
  },
  messageQuoteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  messageQuoteChevron: {
    padding: 2,
  },
  messageQuoteImage: {
    width: 50,
    height: 50,
    borderRadius: 4,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  messageQuoteImageTouchable: {
    width: "100%",
    height: "100%",
  },
  messageQuoteImageContent: {
    width: "100%",
    height: "100%",
  },
  messageQuoteFileIcon: {
    width: 24,
    height: 24,
  },
  documentMediaContainer: {
    flexDirection: "column",
    gap: 0,
    width: "100%",
    borderWidth: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  documentMediaExpandedDesktop: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  documentMediaExpandedMobile: {
    flexDirection: "column",
  },
  documentMediaCard: {
    borderWidth: 0,
    borderRadius: 0,
    overflow: "hidden",
    alignSelf: "flex-start",
  },
  documentMediaCardExpandedDesktop: {
    width: 180,
    minWidth: 180,
    alignSelf: "stretch",
  },
  documentMediaCardMobile: {
    alignSelf: "center",
    width: 180,
  },
  documentAttachmentExpandedDesktop: {
    width: "100%",
    height: "100%",
  },
  documentAttachmentMobile: {
    width: 180,
    height: 180,
    alignSelf: "center",
  },
  documentMediaFooter: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderTopWidth: 1,
  },
  documentIdLeftSlot: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  documentIdText: {
    flex: 1,
    textAlign: "center",
    fontWeight: "600",
  },
  documentInfoButton: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
  },
  documentContextPanel: {
    flex: 1,
    minWidth: 0,
    maxWidth: "100%",
    maxHeight: 220,
    borderWidth: 0,
    borderRadius: 0,
    overflow: "hidden",
  },
  documentContextHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  documentContextTitleWrap: {
    flex: 1,
    minWidth: 0,
    marginRight: 8,
  },
  documentContextCloseButton: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    marginLeft: 8,
    flexShrink: 0,
  },
  documentContextScroll: {
    maxHeight: 170,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  documentContextItem: {
    marginBottom: 10,
  },
  documentContextItemDesktop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  documentContextLabelDesktop: {
    width: 140,
    flexShrink: 0,
    paddingTop: 1,
  },
  documentContextValueDesktop: {
    flex: 1,
  },
  });
}
